version: '3.8'

services:
  frontend:
    build: 
      context: ./eventmanagerfrontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5285/api
    volumes:
      - ./eventmanagerfrontend/.env.development:/app/.env.development
    networks:
      - app-network

  backend:
    build:
      context: ./EventManagerBackend
      dockerfile: Dockerfile
    ports:
      - "5285:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5285
      - FRONTEND_URL=http://frontend:3000
    volumes:
      - ./EventManagerBackend/Environments:/app/Environments  
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "3307:3306"
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge